#!/usr/bin/env python3
"""Generate Cross-Asset Comparison PDF for BTC, ETH, SOL."""
import subprocess
from pathlib import Path

# Results
btc = {'total_return_pct': 821.0, 'win_rate': 49.55, 'max_drawdown_pct': 21.17, 'sharpe_ratio': 3.01, 'total_trades': 111}
eth = {'total_return_pct': 368.89, 'win_rate': 43.27, 'max_drawdown_pct': 23.70, 'sharpe_ratio': 2.72, 'total_trades': 104}
sol = {'total_return_pct': 870.31, 'win_rate': 51.19, 'max_drawdown_pct': 25.46, 'sharpe_ratio': 3.72, 'total_trades': 84}

# Build HTML with escaped CSS braces
html = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Cross-Asset Comparison</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #2c3e50; text-align: center; }
        h2 { color: #34495e; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #3498db; color: white; }
        .best { background-color: #d4edda; font-weight: bold; }
        .metric { color: #7f8c8d; font-size: 0.9em; }
        .footer { margin-top: 40px; text-align: center; color: #95a5a6; font-size: 0.8em; }
    </style>
</head>
<body>
    <h1>Cross-Asset Comparison: Ichimoku + PSAR Strategy</h1>
    <p style="text-align: center;" class="metric">Backtest Period: 2020-01-01 to 2026-05-03 | Timeframe: 4h | Initial Capital: $100,000</p>
    
    <h2>Performance Summary</h2>
    <table>
        <tr><th>Metric</th><th>BTC/USDT</th><th>ETH/USDT</th><th>SOL/USDT</th></tr>
        <tr><td><strong>Total Return (%)</strong></td><td>821.00%</td><td>368.89%</td><td class="best">870.31%</td></tr>
        <tr><td><strong>Win Rate (%)</strong></td><td>49.55%</td><td>43.27%</td><td class="best">51.19%</td></tr>
        <tr><td><strong>Max Drawdown (%)</strong></td><td class="best">21.17%</td><td>23.70%</td><td>25.46%</td></tr>
        <tr><td><strong>Sharpe Ratio</strong></td><td>3.01</td><td>2.72</td><td class="best">3.72</td></tr>
        <tr><td><strong>Total Trades</strong></td><td>111</td><td>104</td><td>84</td></tr>
    </table>
    
    <h2>Key Insights</h2>
    <ul>
        <li><strong>SOL</strong> delivers the highest return (870.31%) and best Sharpe ratio (3.72)</li>
        <li><strong>BTC</strong> offers the lowest drawdown (21.17%) - most conservative</li>
        <li><strong>ETH</strong> shows moderate returns but still strong (368.89%)</li>
        <li>All assets show Sharpe ratios > 2.5, indicating excellent risk-adjusted returns</li>
        <li>PSAR confirmation successfully filters false signals across all assets</li>
    </ul>
    
    <h2>Strategy Configuration</h2>
    <ul>
        <li><strong>Ichimoku Parameters:</strong> Tenkan=9, Kijun=26, Senkou B=52</li>
        <li><strong>PSAR Parameters:</strong> Step=0.02, Max=0.2</li>
        <li><strong>Entry:</strong> Price above cloud AND Tenkan > Kijun AND SpanA > SpanB AND Chikou > Price AND PSAR uptrend</li>
        <li><strong>Exit:</strong> Tenkan < Kijun AND PSAR downtrend</li>
        <li><strong>Commission:</strong> 0.1% | <strong>Slippage:</strong> 0.03%</li>
    </ul>
    
    <div class="footer">Generated by BacktestBot | 2026-05-03</div>
</body>
</html>"""

html_path = Path('/Users/andrey/GitHub_projects/BacktestBot/scripts/cross_asset_comparison.html')
html_path.write_text(html)
print(f"✅ HTML generated: {html_path}")

# Convert to PDF
pdf_path = html_path.with_suffix('.pdf')
try:
    subprocess.run(['wkhtmltopdf', '--enable-local-file-access', str(html_path), str(pdf_path)], check=True)
    print(f"✅ PDF generated: {pdf_path}")
except (subprocess.CalledProcessError, FileNotFoundError):
    try:
        subprocess.run(['weasyprint', str(html_path), str(pdf_path)], check=True)
        print(f"✅ PDF generated (weasyprint): {pdf_path}")
    except:
        print("❌ PDF generation failed - install: brew install wkhtmltopdf")
        exit(1)

print(f"\n✅ PDF ready: {pdf_path}")
